feat: SignUpScreen UI 구현
jay200333/CowGroup pull request #14
Opened 2024-12-29 18:02 UTC by jay200333

👩‍🌾 진행한 작업

✅ 잘못된 입력을 했을 때 Error 표시하는 TextField 구현
✅SignUpScreen UI 구현

📷 작업 결과(사진)

https://github.com/user-attachments/assets/774e4f48-48bf-4425-a059-19219b73c1cb

🗣️ 공유할 내용

X

closed #13

2024-12-29 23:14 UTC, cho960422 requested changes
작업하신 부분에 대한 피드백을 남겨봤습니다. 확인 후 논의할 부분이 있거나 궁금한 점이 있다면 말씀해주세요 :)
그래도 이제 컴포즈 뷰 구성은 좋네요 ㅋㅋ

2024-12-29 23:14 UTC, cho960422 commented on feature/login/src/main/java/com/example/login/component/ValidatingTextField.kt
> +    modifier: Modifier = Modifier,
사소한 거긴 합니다만, 컴포즈팀이 권고하는 modifier의 위치는 컴포저블 파라메터 맨 앞으로 알고 있어요. 확인 부탁드리구 맞으면 이후로 컨벤션을 확정하시죠

2024-12-29 23:14 UTC, cho960422 commented on feature/login/src/main/java/com/example/login/presentation/SignUpScreen.kt
> +    val signUpButtonEnabled = signUpCondition(nickname, email, pw1, pw2, pwPattern)
이 부분들은 View의 책임이 아닌 것 같습니다. 예를 들면 버튼의 활성화 여부를 결정짓는 부분을 View가 알게 되면 UI를 표시하는 역할 이외에 다른 책임이 부여되므로 단일 책임 원칙을 위반한다고 생각해요
또한 변수명 선정에 더 신경써주세요!!
pw1, pw2와 같은 변수명은 코드를 분석하기 전까지 무슨 역할을 하는지 개발자가 알아낼 수 없는 변수명입니다.
저같은 경우 password, passwordConfirm 정도 생각나네요. 하지만 이 또한 password의 변수명과 확장된 버전으로 되어 있기 때문에 좀 더 구체화되어야 한다고 생각합니다:) 죽어도 넘버링은 안 돼요!

2024-12-29 23:14 UTC, cho960422 commented on feature/login/src/main/java/com/example/login/presentation/SignUpScreen.kt
> +fun signUpCondition(
이 로직은 뷰모델에 있어야 할 것 같습니다

2024-12-30 04:49 UTC, jay200333 commented on feature/login/src/main/java/com/example/login/component/ValidatingTextField.kt
> +    modifier: Modifier = Modifier,
컨벤션을 찾아보니 modifier가 반드시 첫번째 위치는 아닌 것 같더라구요. 필수 파라미티 다음으로 쓰는 경우가 많이 보였어요

2024-12-30 04:53 UTC, jay200333 commented on feature/login/src/main/java/com/example/login/presentation/SignUpScreen.kt
> +    val signUpButtonEnabled = signUpCondition(nickname, email, pw1, pw2, pwPattern)
네이밍에 좀 더 신경쓰도록 하겠습니다. 그리고 버튼의 활성화 여부를 결정하는 부분은 viewModel에 두어 수정하도록 하겠습니다.

2024-12-30 04:54 UTC, jay200333 commented on feature/login/src/main/java/com/example/login/presentation/SignUpScreen.kt
> +fun signUpCondition(
좋은 피드백 감사합니다. 😁

2025-01-11 05:36 UTC, merged